version: 2
jobs:
  build:
    working_directory: /opt/app
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Container
          command: |
            docker build -t quay.io/kubecord/websocket:$CIRCLE_SHA1 .
      - deploy:
          name: Publish to Quay
          command: |
            docker login quay.io -u $QUAY_USER -p $QUAY_PWD
            docker push quay.io/kubecord/websocket:$CIRCLE_SHA1
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master